PRAGMA foreign_keys = ON;
CREATE TABLE creators (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,publication_name TEXT,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','active','suspended')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE network_configs (id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,name TEXT NOT NULL,support_status TEXT NOT NULL DEFAULT 'research',referral_signal_version TEXT NOT NULL,monetization_enabled INTEGER NOT NULL DEFAULT 0 CHECK(monetization_enabled IN (0,1)),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE merchant_configs (id TEXT PRIMARY KEY,domain TEXT NOT NULL UNIQUE,name TEXT NOT NULL,support_status TEXT NOT NULL DEFAULT 'research',network_id TEXT REFERENCES network_configs(id),coupon_testing_enabled INTEGER NOT NULL DEFAULT 0,checkout_observation_enabled INTEGER NOT NULL DEFAULT 0,monetization_enabled INTEGER NOT NULL DEFAULT 0,disabled_reason TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE affiliate_identifiers (id TEXT PRIMARY KEY,creator_id TEXT NOT NULL REFERENCES creators(id) ON DELETE CASCADE,network_id TEXT NOT NULL REFERENCES network_configs(id),identifier_type TEXT NOT NULL,identifier_hash TEXT NOT NULL,display_hint TEXT NOT NULL,verification_status TEXT NOT NULL DEFAULT 'unverified' CHECK(verification_status IN ('unverified','pending','verified','rejected')),verified_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(network_id,identifier_type,identifier_hash));
CREATE TABLE protected_referral_events (id TEXT PRIMARY KEY,creator_id TEXT NOT NULL REFERENCES creators(id),affiliate_identifier_id TEXT NOT NULL REFERENCES affiliate_identifiers(id),merchant_id TEXT NOT NULL REFERENCES merchant_configs(id),network_id TEXT NOT NULL REFERENCES network_configs(id),occurred_at TEXT NOT NULL,protection_reason TEXT NOT NULL,policy_version TEXT NOT NULL,checkout_value_minor INTEGER CHECK(checkout_value_minor IS NULL OR checkout_value_minor >= 0),currency TEXT,network_confirmed INTEGER NOT NULL DEFAULT 0 CHECK(network_confirmed IN (0,1)),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE system_flags (key TEXT PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 0 CHECK(enabled IN (0,1)),reason TEXT,policy_version TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO system_flags(key,enabled,reason,policy_version) VALUES ('global_monetization',0,'Fail-safe default until production review','1.0');
CREATE INDEX idx_identifiers_creator ON affiliate_identifiers(creator_id,verification_status);
CREATE INDEX idx_events_creator_date ON protected_referral_events(creator_id,occurred_at DESC);
CREATE INDEX idx_events_merchant_date ON protected_referral_events(merchant_id,occurred_at DESC);
CREATE INDEX idx_events_network_date ON protected_referral_events(network_id,occurred_at DESC);

